const quips = [
  'YOUR EX MOVED ON. SO DID THIS JACKET.',
  'PRE-OWNED. UNLIKE YOUR TASTE.',
  'LUXURY IS KNOWING YOU DIDN’T PAY RETAIL.',
  'SECOND-HAND. FIRST-CLASS TASTE.',
  'DRESS LIKE YOU HAVE TASTE. SPEND LIKE YOU HAVE RENT.',
  'RETAIL THERAPY, WITHOUT THE RETAIL PRICES.',
  'A LITTLE WORN. A LOT MORE INTERESTING.',
  'BUY LESS. FIND BETTER. PRETEND YOU PAID MORE.',
  'YOUR EX WAS SOMEONE ELSE’S PROBLEM TOO. SO WAS THIS JACKET.',
  'SOME THINGS DESERVE A SECOND CHANCE. PEOPLE? DEPENDS. CLOTHES? ABSOLUTELY.',
  'YOUR EX GOT REPLACED. THIS JACKET GOT A BETTER OWNER.',
  'PRE-OWNED, UNLIKE THE RED FLAGS YOU KEEP DATING.',
  'AT LEAST THIS SHIRT HAS BEEN WASHED BEFORE BEING TOXIC.',
  'YOU GAVE YOUR EX CLOSURE. WE GAVE THIS JACKET ANOTHER LIFE.',
  'SOMEBODY BROKE UP WITH THIS JACKET. WE SAW POTENTIAL.',
  'YOUR EX SAID “YOU DESERVE BETTER.” TURNS OUT, THIS JACKET DID TOO.',
  'NOT EVERYTHING ABANDONED IS WORTHLESS. LOOK AT THE JACKET. IGNORE YOUR EX.',
  'THEIR LOSS. YOUR FIT.',
  'SECOND-HAND CLOTHES. FIRST-HAND TRAUMA.',
  'THIS JACKET HAS HISTORY. HOPEFULLY LESS COMPLICATED THAN YOURS.',
  'YOU CAN’T FIX YOUR EX. YOU CAN, HOWEVER, FIX YOUR WARDROBE.',
  'YOUR EX MOVED ON. THIS JACKET UPGRADED.',
  'SOME RELATIONSHIPS SHOULD END. SOME CLOTHES SHOULDN’T.',
  'THE ONLY THING WE’RE RECYCLING IS THE CLOTHES. THE RED FLAGS STAY WITH YOUR EX.',
  'FOUND SOMEONE’S OLD CLOTHES. STILL WAITING TO FIND SOMEONE EMOTIONALLY AVAILABLE.',
  'SUSTAINABLE FASHION: BECAUSE COMMITMENT ISSUES SHOULDN’T APPLY TO CLOTHES.',
  'YOUR DATING HISTORY SAYS “BAD DECISIONS.” YOUR WARDROBE DOESN’T HAVE TO.',
  'AT LEAST THE CLOTHES COME WITH A HISTORY YOU CAN ACTUALLY WEAR.',
  'YOU DON’T NEED ANOTHER SITUATIONSHIP. YOU NEED A BETTER JACKET.',
  'HEALING IS EXPENSIVE. THRIFTING ISN’T.',
  'THERAPY: ₹1,500. THRIFTED JACKET: ₹400. BOTH HAVE CHARACTER.',
  'YOUR BANK ACCOUNT IS RECOVERING. YOUR WARDROBE DOESN’T NEED TO KNOW.',
  'SOMEWHERE BETWEEN “I MISS THEM” AND “I LOOK INCREDIBLE” IS A THRIFTED LEATHER JACKET.'
];

export function ThriftQuip({ index = 0, compact = false }) {
  return <aside className={`thrift-quip ${compact ? 'compact' : ''}`} aria-label="Second Story thought"><span className="quip-spark">✦</span><span>{quips[index % quips.length]}</span></aside>;
}

export function QuipTicker() {
  const line = 'GOOD CLOTHES DESERVE A SECOND OWNER • NEW DOESN’T AUTOMATICALLY MEAN BETTER • WEAR SOMETHING WITH A PAST • ';
  return <div className="quip-ticker" aria-hidden="true"><div>{line}{line}</div></div>;
}
